### PR TITLE
Modified Maya Camera

### PR DESCRIPTION
**Pull request by Przemog1**

### CODE REVIEW

**Comment by devshgraphicsprogramming** [comment]
looks lean and clean

**Comment by devshgraphicsprogramming** [comment]
@Crisspl ?

**Comment by Crisspl** [comment]
It's ready to merge?

**Comment by Przemog1** [comment]
not yet

**Comment by devshgraphicsprogramming** [comment]
I can't really test the BRDF explorer with the normal Maya cam as I don't have an MMB ;)

**Comment by Przemog1** [comment]
> how does it work now?

what exactly

**Comment by Crisspl** [comment]
i meant how close to the desired result :D

**Comment by Przemog1** [comment]
it is almost done i believe

**Comment by Crisspl** [comment]
just a note: every new source file you create should go to /src/... . And learn to add every new source file to cmake

**Pull request merged**
